version: 2

workflows:
  version: 2
  react-stick:
    jobs:
      - build_node_8
      # - release:
      #     requires:
      #       - build_node_8
      #     filters:
      #       branches:
      #         only: master

restore_cache: &restore_cache
  restore_cache:
    keys:
      - npm-cache-{{ checksum "package-lock.json" }}

save_cache: &save_cache
  save_cache:
    key: npm-cache-{{ checksum "package-lock.json" }}
    paths:
      - ~/.npm

codecov: &codecov
  run:
    name: Codecov
    command: bash <(curl -s https://codecov.io/bash)

jobs:
  # Build, lint, run tests
  build_node_8:
    working_directory: ~/react-stick
    docker:
      - image: circleci/node:8-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - run: node -v; npm -v
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run test:coverage
      - *codecov

  # On master and if tests passed, parse the commit history to see if a new release should happen
  # If yes, publish to npm and tag a release on GitHub
  # release:
  #   working_directory: ~/react-stick
  #   docker:
  #     - image: circleci/node:8
  #   steps:
  #     - run: node -v; npm -v
  #     - checkout
  #     - *restore_cache
  #     - run: npm install
  #     - *save_cache
  #     - run: npm run build
  #     - run: npm run semantic-release